services:
  db:
    image: postgis/postgis:16-3.4
    # restart: always
    ports:
      - '5432:5432'
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
  
  redis:
      image: redis:7.4.0-alpine3.20
      command: redis-server --appendonly yes --requirepass 'redis'
      volumes:
        - redis:/data
      ports:
        - 6379:6379

volumes:
  db: {}
  redis: {}
